<a href="https://colab.research.google.com/github/CharvRaj/LMS-system/blob/main/2_RegressionTensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Linear Regression using TensorFlowxt**

Objective: Build a simple linear regression model using only Tensors, Variables and GradientTape.

Suppose we have number of hours a student studies and their marks. Can we predict marks for a new student?

**Create the Dataset**

In [1]:
import tensorflow as tf

x = tf.constant([1, 2, 3, 4, 5], dtype=tf.float32)
y = tf.constant([30, 40, 50, 60, 70], dtype=tf.float32)

print("X:", x)
print("Y:", y)

X: tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float32)
Y: tf.Tensor([30. 40. 50. 60. 70.], shape=(5,), dtype=float32)


**Create Weights and Bias**

In [2]:
w = tf.Variable(0.0)
b = tf.Variable(0.0)

print("Weight:", w)
print("Bias:", b)

Weight: <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.0>
Bias: <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.0>


These are our initial guesses

**Prediction**

In [3]:
def predict(x):
  return w * x + b


In [4]:
#Test
print(predict(x))

tf.Tensor([0. 0. 0. 0. 0.], shape=(5,), dtype=float32)


Initially:  
w = 0,  
b = 0

So prediction will be:  
[0, 0, 0, 0, 0]

But actual values are:  
[30, 40, 50, 60, 70]

Clearly our model is bad

**Calculate Error/Loss**

In [5]:
# Mean Square Error(MSE)
def loss_function(y_true, y_pred):
  return tf.reduce_mean(tf.square(y_true - y_pred))    # return tf.reduce_mean((y_true-y_pred)**2)

In [6]:
predictions = predict(x)

loss = loss_function(y, predictions)

print("Prediction:", predictions)
print("Loss:", loss)

Prediction: tf.Tensor([0. 0. 0. 0. 0.], shape=(5,), dtype=float32)
Loss: tf.Tensor(2700.0, shape=(), dtype=float32)


Loss is huge because our predictions are terrible.

**Use GradientTape**

Using `GradientTape`, TensorFlow will change `w` and `b`

In [7]:
with tf.GradientTape() as tape:
  predictions = predict(x)
  loss = loss_function(y,predictions)

gradients = tape.gradient(loss, [w, b])

print("Gradients:",gradients)



Gradients: [<tf.Tensor: shape=(), dtype=float32, numpy=-340.0>, <tf.Tensor: shape=(), dtype=float32, numpy=-100.0>]


**Update the variables**

Gradient tells us how the loss changes. We use it to update our weight and bias.

In [8]:
learning_rate = 0.01

In [9]:
w.assign_sub(learning_rate * gradients[0])
b.assign_sub(learning_rate * gradients[1])

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=1.0>

In [10]:
print("Updated Weight:", w)
print("Updated Bias:", b)

Updated Weight: <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.3999998569488525>
Updated Bias: <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>


we can see that the values have changed

A model learns by repeating this process many times

**Put it inside a Training Loop**

In [11]:
learning_rate = 0.01
epochs = 1000

for epoch in range(epochs):

  with tf.GradientTape() as tape:
    predictions = predict(x)
    loss = loss_function(y, predictions)

  gradients = tape.gradient(loss, [w, b])

  w.assign_sub(learning_rate * gradients[0])
  w.assign_sub(learning_rate * gradients[1])

  if epoch % 100 == 0:
    print("Epoch", epoch, "Loss", loss.numpy())

Epoch 0 Loss 1592.56
Epoch 100 Loss 66.30612
Epoch 200 Loss 66.30612
Epoch 300 Loss 66.30612
Epoch 400 Loss 66.30612
Epoch 500 Loss 66.30612
Epoch 600 Loss 66.30612
Epoch 700 Loss 66.30612
Epoch 800 Loss 66.30612
Epoch 900 Loss 66.30612


At the beginning, our model's predictions are poor, so the loss is high. During training, GradientTape calculates the gradients and we update w and b. Therefore, the loss decreases. When the loss stops decreasing, it means the model has reached a point where further updates are not improving it significantly.

**See What the Model Learned**

In [12]:
print("Final Weight:", w.numpy())
print("Final Bias:", b.numpy())

Final Weight: 15.428571
Final Bias: 1.0


Model: y = 15x+1

which we learned from the data

**Make a Prediction**

In [13]:
# what if student studies for 6 hours
new_x = tf.constant(6.0)

prediction = predict(new_x)

print("Predicted Marks:", prediction.numpy())

Predicted Marks: 93.57143
